### ISSUE TITLE
Open to a PR?

### ISSUE THREAD

**Issue by matthewfcarlson** [FakeDomi/EasyAutoCrafting#1]
Would you be open to a PR that added support for architectury? https://docs.architectury.dev

This means the mod would support both Forge and Fabric

**Comment by FakeDomi** [comment]
Isn't that a bit overkill for a tiny mod like this? Also, I don't intend to publish a forge build, as I'm primarily making mods for myself. If you want to do this, go ahead, but publishing will also be up to you then :)

**Comment by matthewfcarlson** [comment]
I'll just make a forge version of this mod myself then, and not bother with architectury. I probably won't publish it since it's just for me and my brother

**Comment by matthewfcarlson** [comment]
Thanks for responding!
