### ISSUE TITLE
Transfer api doesn't seem to be supported for output

### ISSUE THREAD

**Issue by MattiDragon** [FakeDomi/EasyAutoCrafting#6]
You seem to have some transfer api implementation (perhaps for input?), but lack it for outputs. This breaks mods like [extended drawers](https://github.com/MattiDragon/ExtendedDrawers) that exclusively use the transfer api. 

Original report: mattidragon/extendeddrawers#31

**Comment by FakeDomi** [comment]
I indeed do not use the transfer api for output as there's no way to specify that items should merge with existing stacks first instead of going into the first available slot. But thinking about it now, I could make it use the transfer api as a fallback if there's no valid vanilla inventory found.
