### ISSUE TITLE
Versions 1.6 and 1.7 crash on Minecraft version 1.19.4

### ISSUE THREAD

**Issue by bawjames** [FakeDomi/EasyAutoCrafting#7]
Both mod versions 1.6 and 1.7 crash on Minecraft version 1.19.4. These versions of the mod work on Minecraft version 1.19.

Mods loaded:
 - Fabric API
 - EasyAutoCrafting

Minecraft version: 1.19.4
Fabric Loader version: 0.14.18
Fabric API version: 0.76.0
EasyAutoCrafting version: 1.7
[crash report](https://github.com/FakeDomi/EasyAutoCrafting/files/11163787/crash-2023-04-05_23.42.44-server.txt)

Minecraft version: 1.19.4
Fabric Loader version: 0.14.18
Fabric API version: 0.76.0
EasyAutoCrafting version: 1.6
[crash report](https://github.com/FakeDomi/EasyAutoCrafting/files/11163609/crash-2023-04-05_23.33.28-server.txt)

Same conditions causing crash. A recipe is inserted into dropper, with a crafting table and a barrel containing the ingredients placed adjacent, touching the dropper - the exact arrangement from the showcase video. Any recipe used causes a crash **at the moment the dropper button is pressed**.

Works just fine on Minecraft version 1.19 with mod version 1.7 (Fabric version 0.14.19, Fabric API version 0.58.0).

Great mod btw, very simple and effective implementation - love it!

**Comment by FakeDomi** [comment]
Mojang is smoking some of the good stuff apparently. Introducing (unnecessary) breaking changes in minor versions - they did the same in 1.19.3 already.

**Comment by FakeDomi** [comment]
Published a 1.19.4 compatible build now
