### ISSUE TITLE
Dropper items are removed when inventory is above the dropper.

### ISSUE THREAD

**Issue by Oscarito103** [FakeDomi/EasyAutoCrafting#8]
If you place the inv (input) on top of the dropper the items are removed when something is crafted and wont craft any more unless you use a hopper.

**Comment by FakeDomi** [comment]
Can you describe the issue in more detail? Or maybe make a short video. I can't reproduce it.

https://user-images.githubusercontent.com/1492543/230709403-f7445ca3-3d59-46b4-b7d9-4d63cb52b78b.mp4

**Comment by Oscarito103** [comment]
Maybe its some of the mods i use. I use fabric with optimizing mods and carpet.

**Comment by FakeDomi** [comment]
Closing this for now, feel free to post here if you have further information
