### ISSUE TITLE
[FEATURE REQUEST] The ability for the dropper to access 2 inventories at the same time

### ISSUE THREAD

**Issue by Mason-931** [FakeDomi/EasyAutoCrafting#9]
First off, I want to say that i LOVE this mod. i've been implementing it into my guardian farm to auto craft the blocks, but when i'm crafting dark prismarine i find that the "input" inventory always ends up full with black dye and no more shards can get in, breaking the crafting. I attempted to simply have an input on the back of the dropper and on the side for each crafting item, but unfortunately that doesn't work. Is there a possibility that this could be implemented?

**Comment by FakeDomi** [comment]
There's a config option to enable 3x3 inventory searching behind the dropper

**Comment by Mason-931** [comment]
Oh, well in that case, AWESOME! I guess I could throw in the sugeestion of editing the config in mod menu?

**Comment by FakeDomi** [comment]
It's not really something you enable on-the-fly so I'd say it's not worth the effort.
